databases:
  - name: smakan
    databaseName: smakan
    user: dylan

services:
  - type: web
    name: smakan
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn smakan.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smakan
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4